title: BetaNLP Homepage
page-top-title: BetaNLP Homepage
top-section-bg-text: Pioneering the Next Generation of NLP.
home-subtitle: BetaNLP
copyright-text: '&copy; Jerry Yin 2024. All Rights Reserved. Template by Jerry Yin From <a href="https://github.com/JerryYin777/JerryYin777.github.io">This Repo</a>.'
